# Generated by Django 4.2.11 on 2024-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
